# VARIABLES
PACKAGE="github.com/bazilio91/throne"
BINARY_NAME="main"

default: help

# build all
build:
	@echo "--> Building application"
	@env GOOS=linux go build $(BINARY_NAME).go
	@echo "--> done!"
